/* Main.c file generated by New Project wizard
 *
 * Created:   mié. sep. 15 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include "lcd.h"
#include <stdint.h>

int main (void)
 { 
   // Write your code here
       /* Enable clocks for GPIO ports */
   RCC->APB2ENR |= 0xFC;
   /* PA0-PA7 as outputs */
   GPIOA->CRL = 0x33333333;
   /* PB7-PB5 as outputs */
   GPIOB->CRL = 0x33344444;
    lcd_init();
    lcd_sendData('H');
     lcd_sendData('E');
     lcd_sendData('H');
     lcd_sendData('H');
   while (1){}
   }   
 
 
