/* Main.c file generated by New Project wizard
 *
 * Created:   mié. sep. 15 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include "lcd.h"
#include <stdint.h>
#include "delay.h"
#include "teclado.h"
#include "mef.h"

int main (void)
 {  
	uint8_t dato = 0;
	RCC->APB2ENR |= 0xFC;       /* Enable clocks for GPIO ports */
	GPIOA->CRL = 0x33333333;/* PA0-PA7 as outputs */
	GPIOA->CRH = 0x44444333;
	GPIOB->CRL = 0x44444443;
	lcd_init();
	MEF_Init();
	while (1) { 
			MEF_Update();
			delay_us(1000 );
    }
}   

